plugins {
    id 'java-library'
    id 'org.springframework.boot' version '4.0.3'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'maven-publish'
}
group = 'org.digitalmind'
version = '4.0.0'

ext {
    mapstructVersion = '1.6.3'
    lombokVersion = '1.18.44'
}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}
tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}
bootJar {
    enabled = false
}
jar {
    archiveBaseName = "event-orchestrator"
    enabled = true
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        name = "digitalmind"
        url = uri("https://maven.pkg.github.com/Digital-Mind-Solutions/maven-repository")
        credentials {
            username = project.findProperty("dm.ghub.user") ?: System.getenv("DM_GITHUB_USER")
            password = project.findProperty("dm.ghub.key") ?: System.getenv("DM_GITHUB_TOKEN")
        }
    }
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation "org.springframework.boot:spring-boot-starter-security"

    implementation "org.digitalmind.buildingblocks.core:dtobase:4.0.0"
    implementation "org.digitalmind.buildingblocks.core:beanutils:4.0.0"
    implementation "org.digitalmind.buildingblocks.core:spelutils:4.0.0"
    implementation "org.digitalmind.buildingblocks.core:networkutils:4.0.0"
    implementation "org.digitalmind.buildingblocks.core:requestcontext:4.0.0"
    implementation "org.digitalmind.buildingblocks.templating:templating-core:4.0.0"
    implementation "org.digitalmind.buildingblocks.core:jpautils:4.0.0"

    implementation 'commons-io:commons-io:2.18.0'

    implementation "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    implementation "org.mapstruct:mapstruct:${mapstructVersion}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"

    implementation 'com.github.jknack:handlebars:4.3.1'
    implementation 'com.github.jknack:handlebars-helpers:4.3.1'
    implementation 'com.github.jknack:handlebars-guava-cache:4.3.1'
    implementation 'com.github.jknack:handlebars-jackson2:4.3.1'
    implementation 'org.beryx:handlebars-java-helpers:0.4.1'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.2'
    implementation 'org.springframework.plugin:spring-plugin-core:4.0.0'
}

publishing {
    repositories {
        maven {
            name = "digitalmind"
            url = uri("https://maven.pkg.github.com/Digital-Mind-Solutions/maven-repository")
            credentials {
                username = project.findProperty("dm.ghub.user") ?: System.getenv("DM_GITHUB_USER")
                password = project.findProperty("dm.ghub.key") ?: System.getenv("DM_GITHUB_TOKEN")
            }
        }
    }
    publications {
        eventOrchestrator(MavenPublication) {
            from components.java
        }
    }
}
